name: TicTacToe
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - numpy>=1.16,<2
  - matplotlib>=3.0.2,<4
  - prettytable>=0.7.2,<1
  - scikit-learn>=0.20.2,<1
  - python-graphviz>=0.8.4,<1
  - graphviz
# - tensorflow==1.10.0
# - keras==2.2.2