name: TicTacToe
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - numpy>=1.16,<2
  - matplotlib>=3.0.2,<4
  - prettytable>=0.7.2,<1
  - scikit-learn>=0.20.2,<1
  - python-graphviz>=0.8.4,<1
  - graphviz>=2.42.3
  - pandas>=1.0
  - tensorflow>=2.1.0
  #- keras>=2.2.2